default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # See https://docs.astral.sh/ruff/rules/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]

      # Run the formatter.
      - id: ruff-format
