site_name: dbt-airflow Documentation
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.follow
repo_name: gmyrianthous/dbt-airflow
repo_url: https://github.com/gmyrianthous/dbt-airflow

nav:
  - Overview: index.md
  - Examples:
      - Basic DAG: examples/example_dag_basic.md
      - DAG with Extra Tasks: examples/example_dag_extra_tasks.md
      - DAG without task groups: examples/example_dag_sub_task_groups.md
  - Contributing to dbt-airflow: contributing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature_annotations: true
            separate_signature: true
