"""
This module contains functionality that is used when it comes to processing and extracting
information from the `manifest.json` file that gets generated by several dbt commands.
"""
import json
import logging
import os

from exceptions import ManifestNotFound


class ManifestProcessor:

    def __init__(self):
        self.data = None
        self.path = os.path.abspath('target/manifest.json')


    def load(self) -> None:
        """
        Loads the manifest.json file created by dbt
        """
        if not os.path.isfile(self.path):
            raise ManifestNotFound(
                f'manifest.json file was not found in {self.path}. '
                f'Make sure that you are running dbt-airflow from your dbt project directory'
            )

        with open(self.path, 'r') as f:
            self.data = json.load(f)
