name: Validate Pull Request on main branch

on:
  pull_request:
    branches:
      - 'main'

env:
  POETRY_VERSION: "1.3"
  PYTHON_VERSION: "3.11"

jobs:
  validate_pull_request:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache virtual environment and pip
        uses: actions/cache@v3.2.3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          pip install 'poetry~=${{ env.POETRY_VERSION }}'
          poetry config virtualenvs.in-project true
          poetry install --with dev --no-interaction --no-ansi --sync
      - name: Validate Commit Messages in Pull Request
        run: poetry run cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
